# Generated by Django 4.1.5 on 2023-05-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageblocks', '0004_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageblock',
            name='language',
        ),
        migrations.AddField(
            model_name='pageblock',
            name='i18n_data',
            field=models.JSONField(default=dict),
        ),
    ]
